stages:
    - build
    - policies

before_script:
     - if [ ! -d "spack" ]; then
            git clone https://github.com/spack/spack.git;
          fi
cache:
        paths:
            - spack/
job 1:
    stage: build
    script:
        - echo "building"
        - ls
        - if [ ! -d "xsdk-ci-test" ]; then
            git clone https://github.com/xsdk-project/xsdk-ci-test.git;
          fi
        - more README
        - cd spack/bin/
        - sh ../../xsdk-ci-test/spack xSDK-install.sh
    cache:
        paths:
            - xsdk-ci-test/
job 2:
    stage: policies
    script:
        - echo "policies"
        - more README
    cache:
        paths:
            - spack/

