stages:
    - build


before_script:
     - if [  -d "spack" ]; then
            rm -rf spack;
        fi
     - if [  -d "xsdk-tests-ci" ]; then
          rm -rf xsdk-tests-ci;
        fi
     - git clone https://github.com/spack/spack.git;
     - git clone https://github.com/xsdk-project/xsdk-ci-test.git xsdk-tests-ci;
     - bash xsdk-tests-ci/spack/xSDK-install.sh $(pwd)/spack/bin/spack
     - result=$(echo $?)
     - if [ $result -gt 0 ];then
     -     return $result
     - fi
     - bash xsdk-tests-ci/policy/test-policy-all.sh $(pwd)/spack "phist petsc"

job 1:
    image: perrinel/fedora-xsdk
    stage: build
    script:
        - echo "Building for fedora"
    artifacts:
        paths:
        - report/phist/report_m1.log
        - report/phist/report_m2.log
        - report/phist/report_m7.log
        - report/gcc@8.3.1/phist/report_m13.log
        expire_in: 1 week

job 2:
    image: perrinel/ubuntu-xsdk
    stage: build
    script:
        - echo "Building for ubuntu"
    artifacts:
        paths:
        - report/phist/report_m1.log
        - report/phist/report_m2.log
        - report/phist/report_m7.log
        - report/gcc@7.4.0/phist/report_m13.log
        - report
        expire_in: 1 week

        
