stages:
    - build
    - policies

job 1:
    stage: build
    script:
        - echo "building"
        - if [ ! -d "xsdk" ]; then
            git clone https://github.com/xsdk-project/xsdk-ci-test.git;
          fi
        - more README
    cache:
        paths:
            - xsdk-ci-test/
job 2:
    stage: policies
    script:
        - echo "policies"
        - more README
    cache:
        paths:
            - spack/

