stages:
    - build
    - policies

before_script:
     - cd ..
     - if [ ! -d "spack" ]; then
            git clone https://github.com/spack/spack.git;
          fi
     - pwd
     - ls
cache:
        paths:
            - spack/
job 1:
    stage: build
    script:
        - echo "building"
        - pwd
        - ls
        - pwd
        - sh xsdk-tests-ci/spack/xSDK-install.sh $pwd/spack/bin/spack
        - mkdir can_build_here_test
        - ls
        - uname -s
        - case "$(uname -s)" in
            Darwin)
                echo 'Darwin'
            ;;
            Linux)
                echo 'Linux'
            ;;
          esac
        
job 2:
    stage: policies
    script:
        - echo "policies"
        - more README
