stages:
    - build
    - policies

before_script:
     - cd ..
     - if [ ! -d "spack" ]; then
            git clone https://github.com/spack/spack.git;
          fi
     - pwd
     - ls
     - ls spack
cache:
        paths:
            - spack/
job 1:
    stage: build
    script:
        - echo "building"
        - pwd
        - ls
        - pwd
        - cd ..
        - ls
        - pwd
        - cd spack/bin/
        - sh ../../xsdk-ci-test/spack xSDK-install.sh
job 2:
    stage: policies
    script:
        - echo "policies"
        - more README
